### ISSUE TITLE
Define All Mod Types 

### ISSUE THREAD

**Issue by effs** [E1337Kat/cyberpunk2077_ext_redux#33]
Some kind of summary that's easily readable, plus actual implementation for each mod type.

By my reckoning, this:

1. Files only

- [/] Archives only (with or without options)
- [ ] CET (+ possibly archives) #13 and #25 
- [ ] Redscript (+ possibly archives) #27  
- [ ] Red4Ext (+ possibly archives) #5 
- [ ] TweakDB (+ possibly archives) #6 - do these always come with one of the other types?
- [ ] ArchiveXL (+ possibly archives) #28  - do these always come with one of the other types? 
- [ ] INI (engine\config\platform\pc) #29 
- [ ] Other config only (xml/json) #30
- [ ] Reshade #8
- [ ] LUT #31
- [ ] Enabling mods (like CET, Redscript, etc.) #32
- [ ] Tools (like CSVMerge) #32

2. Tool or other modification required

- [ ] Archives requiring CSVMerge 
- [ ] Config changes to insert things like a new keymapping
