### ISSUE TITLE
0.3.0 Release Checklist

### ISSUE THREAD

**Issue by effs** [E1337Kat/cyberpunk2077_ext_redux#89]
- [x] Everything in 0.3.0 milestone completed
- [x] Version updated for package
- [x] Tagged
- [x] Release Notes written
- [x] Changelog updated
- [x] Nexus docs/images etc. updated
- [x] Manually tested (see how the test suite fares?)
- [x] Release created on GH
- [x] Uploaded to Nexus
- [x] Announced
    - [x] Discords
    - [x] Where else?

**Comment by E1337Kat** [comment]
It was released! ^_^
